### ISSUE TITLE
Add api login + logout

### ISSUE THREAD

**Issue by SonNguyen0406** [SonNguyen0406/Book-Shop-Project#2]
# Task 
- [x] Viết API login + logout
- [x] Call APi Login
- [ ] Add logout view + Call API logout
